trigger: none

pool:
  name: EMA-WEU-NPD-AZ-POOL

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'npm install'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: set BUSINESS_PROCESS=$(BUSINESS_PROCESS) && set ENVIRONMENT=$(ENVIRONMENT) && set DATABRICKS_TOKEN=$(DATABRICKS_TOKEN) && set AZURE_ORGANIZATION=$(AZURE_ORGANIZATION) && set PROJECT_NAME=$(PROJECT_NAME) && set AZURE_TOKEN=$(AZURE_TOKEN) && set TEST_PLAN_ID=$(TEST_PLAN_ID) && set POWERBI_SERVICE_USER=$(POWERBI_SERVICE_USER) && set POWERBI_SERVICE_PASSWORD=$(POWERBI_SERVICE_PASSWORD) && set POWERBI_REPORT_USER=$(POWERBI_REPORT_USER) && set POWERBI_REPORT_PASSWORD=$(POWERBI_REPORT_PASSWORD) && npx playwright test -g $(E2E_TAG) --retries=1 --workers=5
  displayName: 'Run E2E Workflow'
  env:
    CI: 'true'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)\test\data\generated_data
    artifact: generated_data
    publishLocation: 'pipeline'
  condition: succeededOrFailed()

- script: set BUSINESS_PROCESS=$(BUSINESS_PROCESS) && set ENVIRONMENT=$(ENVIRONMENT) && set DATABRICKS_TOKEN=$(DATABRICKS_TOKEN) && set AZURE_ORGANIZATION=$(AZURE_ORGANIZATION) && set PROJECT_NAME=$(PROJECT_NAME) && set AZURE_TOKEN=$(AZURE_TOKEN) && set TEST_PLAN_ID=$(TEST_PLAN_ID) && set POWERBI_SERVICE_USER=$(POWERBI_SERVICE_USER) && set POWERBI_SERVICE_PASSWORD=$(POWERBI_SERVICE_PASSWORD) && set POWERBI_REPORT_USER=$(POWERBI_REPORT_USER) && set POWERBI_REPORT_PASSWORD=$(POWERBI_REPORT_PASSWORD) && npx playwright test -g $(TAGS) --retries=1 --workers=5
  displayName: 'Run Regression Tests'
  env:
    CI: 'true'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)\playwright-report
    artifact: playwright-report
    publishLocation: 'pipeline'
  condition: succeededOrFailed()